//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int MoveHorizontal = 0;
    public const int MoveVertical = 1;
    public const int Action = 2;
    public const int Escape = 3;
}
